name: CI


on:

  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup do NodeJS
        uses: actions/checkout@v3.0.0
        with: 
          node-version: 20.17.0

      - name: Instalação do Mocha para teste e dos pacotes
        run: |
          cd src;
          npm install -g mocha;
          npm install

      - name: Teste de Validação
        run: mocha src/test/convert.js

      - name: Criando a imagem docker
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./src
          file: ./Dockerfile
          push: true
          tags: |
            augukelsch/aula-conversao-temperatura:v1
            augukelsch/aula-conversao-temperatura:latest
